### ISSUE TITLE
 why Postraphile isn't exposing the parent table instead of the partition tables.

### ISSUE THREAD

**Issue by divya-sk** [graphile/postgraphile#1991]
I am raising one question addressing why Postraphile isn't exposing the parent table instead of the partition tables.

**Comment by benjie** [comment]
Why: because Postgres didn’t support partition tables when v4 came about and no-one added support until recently.

What can you do about it: this is fixed in version 5, and you can also work around it in V4 with the option detailed in this PR: https://github.com/graphile/graphile-engine/pull/801

**Comment by divya-sk** [comment]
we are using  "postgraphile": "4.13.0", still facing the same issues 

   graphqlRoute: "/shield/graphql",
      graphiqlRoute: "/shield/graphiql",
      eventStreamRoute: "/shield/graphql/stream",
      ownerConnectionString: process.env.OWNER_CONNECTION_STRING,
      watchPg: true,
      graphiql: true,
      enhanceGraphiql: true,
      pgUsePartitionParents: true,
      enableCors: false,
      disableWarning: true,
      statement_timeout: "3600000",
      appendPlugins: [
        require("@graphile-contrib/pg-simplify-inflector"),
        require("postgraphile-plugin-connection-filter"),
      ],
    }
  ),
 this is the piece of code we using.

**Comment by benjie** [comment]
As shown in the link above, the option goes inside of graphileBuildOptions
